feature/rabbitmq-guest-user
ONSdigital/census-rm-docker-dev pull request #72
Opened 2020-09-29 06:28 UTC by apolloakora

Security best practise urges us not to use default account usernames and passwords.

- **`rmquser`** (is the new standard rabbitmq user)
- **`rmqmanager`** (is new metrics and monitoring user)
- guest account to be deleted manually after successful release

Important : Do not forget when testing to give a BRANCH variable feature/rabbitmq-guest-user so that apply-kubernetes can download the correct tmp_rm_kube

2020-09-29 06:29 UTC, apolloakora commented
![](https://github.trello.services/images/mini-trello-icon.png) [stop using guest username for rabbitmq (8)](https://trello.com/c/Ok5vnmxD/1440-stop-using-guest-username-for-rabbitmq-8)

2020-09-30 10:20 UTC, NickGrantONS commented on .env
> +RABBITMQ_PASSWORD=rmqp455w0rd
sorry to be a pain, but number substitution of of letters in dictionary words doesn't add any security... it just makes it harder to remember the password; more of a pain when doing local dev work. Also, this is a public repo, so the password is there for all to see, which is not a problem, because this is just for dev environments... but I don't see the point in making it harder to remember and type!

2020-09-30 10:21 UTC, NickGrantONS requested changes
See comments: we shouldn't needlessly be making our lives harder, as developers. Good work though

2020-10-01 13:42 UTC, apolloakora commented on .env
> +RABBITMQ_PASSWORD=rmqp455w0rd
Nick fair point - I've simplified the password so that local dev work is not affected.

2021-01-22 16:12 UTC, closed without merging